name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Backend checks
        run: python scripts/run_backend_checks.py
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ui-next
        run: npm install
      - name: Frontend checks
        working-directory: ui-next
        run: npm run check
